import hashlib
import json
import os
import re
from dataclasses import dataclass
from datetime import date
from itertools import chain
from pathlib import Path
from typing import Iterable

import chromadb
from cryptography.fernet import Fernet
from dotenv import load_dotenv
from sentence_transformers import SentenceTransformer
from tqdm import tqdm

load_dotenv()

DEFAULT_MODEL_NAME = "Qwen/Qwen3-Embedding-0.6B"
DATE_STEM_RE = re.compile(r"^(\d{4})_(\d{2})_(\d{2})$")


@dataclass(frozen=True)
class MarkdownFile:
    rel: str
    fingerprint: str
    text: str


def getenv_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


def required_env(name: str) -> str:
    value = os.getenv(name)
    if not value:
        raise ValueError(f"{name} must be set")
    return value


def chunks(text: str, size: int = 900, overlap: int = 150):
    # rough char chunking; close enough for v1
    i = 0
    while i < len(text):
        yield text[i : i + size]
        i += size - overlap


def build_fernet_from_env() -> Fernet | None:
    key_value = os.getenv("S3_ENCRYPTION_KEY")
    if not key_value:
        return None

    try:
        return Fernet(key_value.encode("utf-8"))
    except Exception as exc:
        raise ValueError("S3_ENCRYPTION_KEY must be a Fernet key generated by Fernet.generate_key()") from exc


def decrypt_if_needed(data: bytes, fernet: Fernet | None) -> bytes:
    if fernet is None:
        return data
    return fernet.decrypt(data)


def encrypt_if_needed(data: bytes, fernet: Fernet | None) -> bytes:
    if fernet is None:
        return data
    return fernet.encrypt(data)


def date_from_rel(rel: str) -> date | None:
    match = DATE_STEM_RE.match(Path(rel).stem)
    if not match:
        return None
    year, month, day = [int(part) for part in match.groups()]
    return date(year, month, day)


def in_date_window(rel: str) -> bool:
    file_date = date_from_rel(rel)
    if file_date is None:
        return True

    start = os.getenv("SHARD_DATE_START")
    end = os.getenv("SHARD_DATE_END")
    if start and file_date < date.fromisoformat(start):
        return False
    if end and file_date > date.fromisoformat(end):
        return False
    return True


def in_hash_shard(rel: str) -> bool:
    count = int(os.getenv("SHARD_COUNT", "1"))
    index = int(os.getenv("SHARD_INDEX", "0"))
    if count < 1:
        raise ValueError("SHARD_COUNT must be at least 1")
    if index < 0 or index >= count:
        raise ValueError("SHARD_INDEX must be between 0 and SHARD_COUNT - 1")
    digest = hashlib.sha256(rel.encode("utf-8")).digest()
    return int.from_bytes(digest[:8], "big") % count == index


def should_index_rel(rel: str) -> bool:
    return in_date_window(rel) and in_hash_shard(rel)


def iter_local_markdown() -> Iterable[MarkdownFile]:
    logseq_dir = Path(required_env("LOGSEQ_DIR"))
    patterns = [pattern.strip() for pattern in os.getenv("LOCAL_MARKDOWN_GLOBS", "journals/2025_*.md").split(",")]
    paths = chain.from_iterable(logseq_dir.rglob(pattern) for pattern in patterns if pattern)

    for path in paths:
        rel = str(path.relative_to(logseq_dir))
        if not should_index_rel(rel):
            continue
        yield MarkdownFile(
            rel=rel,
            fingerprint=str(path.stat().st_mtime),
            text=path.read_text(errors="ignore"),
        )


def s3_client():
    import boto3

    return boto3.client("s3", region_name=os.getenv("AWS_REGION"))


def iter_s3_markdown(fernet: Fernet | None) -> Iterable[MarkdownFile]:
    bucket = required_env("S3_BUCKET")
    prefix = os.getenv("S3_MARKDOWN_PREFIX", "")
    client = s3_client()
    paginator = client.get_paginator("list_objects_v2")

    for page in paginator.paginate(Bucket=bucket, Prefix=prefix):
        for obj in page.get("Contents", []):
            key = obj["Key"]
            if not key.endswith(".md"):
                continue
            rel = key[len(prefix) :].lstrip("/") if prefix else key
            if not should_index_rel(rel):
                continue
            body = client.get_object(Bucket=bucket, Key=key)["Body"].read()
            plaintext = decrypt_if_needed(body, fernet)
            yield MarkdownFile(
                rel=rel,
                fingerprint=f'{obj.get("ETag", "").strip(chr(34))}:{obj.get("LastModified", "")}',
                text=plaintext.decode("utf-8", errors="ignore"),
            )


def serialize_embedding_records(records: list[dict]) -> bytes:
    return "\n".join(json.dumps(record, separators=(",", ":")) for record in records).encode("utf-8")


def embedding_output_key(payload: bytes) -> str:
    prefix = os.getenv("S3_EMBEDDINGS_PREFIX", "embeddings/").rstrip("/")
    shard_index = os.getenv("SHARD_INDEX", "0")
    digest = hashlib.sha256(payload).hexdigest()[:16]
    return f"{prefix}/shard-{shard_index}/{digest}.jsonl"


def write_embeddings_to_s3(records: list[dict], fernet: Fernet | None) -> None:
    if not records or not getenv_bool("WRITE_EMBEDDINGS_TO_S3"):
        return
    bucket = required_env("S3_BUCKET")
    payload = serialize_embedding_records(records)
    encrypted_payload = encrypt_if_needed(payload, fernet)
    key = embedding_output_key(payload)
    s3_client().put_object(Bucket=bucket, Key=key, Body=encrypted_payload)
    print(f"Wrote {len(records)} embedding records to s3://{bucket}/{key}")


def write_embeddings_to_local(records: list[dict], fernet: Fernet | None) -> None:
    if not records or not getenv_bool("WRITE_EMBEDDINGS_TO_LOCAL"):
        return
    if fernet is None:
        raise ValueError("S3_ENCRYPTION_KEY must be set when WRITE_EMBEDDINGS_TO_LOCAL is true")

    payload = serialize_embedding_records(records)
    encrypted_payload = encrypt_if_needed(payload, fernet)
    output_path = Path(required_env("LOCAL_EMBEDDINGS_DIR")) / embedding_output_key(payload)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(encrypted_payload)
    print(f"Wrote {len(records)} encrypted embedding records to {output_path}")


def load_state() -> dict:
    state_file = Path(os.getenv("STATE_FILE", "index_state.json"))
    if state_file.exists():
        return json.loads(state_file.read_text())
    return {}


def save_state(state: dict) -> None:
    state_file = Path(os.getenv("STATE_FILE", "index_state.json"))
    state_file.write_text(json.dumps(state, indent=2))


def main() -> None:
    source = os.getenv("MARKDOWN_SOURCE", "local").lower()
    fernet = build_fernet_from_env()
    state = load_state()
    model_name = os.getenv("MODEL_NAME", DEFAULT_MODEL_NAME)
    hugging_face_cache = os.getenv("HF_CACHE_DIR", "/models")

    model = SentenceTransformer(local_files_only=True, model_name_or_path=model_name, cache_folder=hugging_face_cache)

    write_to_chroma = getenv_bool("WRITE_EMBEDDINGS_TO_CHROMA", True)
    collection = None
    if write_to_chroma:
        db_dir = required_env("DB_DIR")
        collection_name = required_env("COLLECTION")
        client = chromadb.PersistentClient(path=db_dir)
        collection = client.get_or_create_collection(collection_name)

    if source == "local":
        markdown_files = iter_local_markdown()
    elif source == "s3":
        markdown_files = iter_s3_markdown(fernet)
    else:
        raise ValueError("MARKDOWN_SOURCE must be 'local' or 's3'")

    for markdown_file in tqdm(markdown_files):
        if markdown_file.rel in state and state[markdown_file.rel]["fingerprint"] == markdown_file.fingerprint:
            continue

        docs, ids, metas = [], [], []
        for j, chunk in enumerate(chunks(markdown_file.text)):
            if chunk.strip():
                ids.append(f"{markdown_file.rel}::{j}")
                docs.append(chunk)
                metas.append({"path": markdown_file.rel, "chunk": j})

        if not docs:
            state[markdown_file.rel] = {"fingerprint": markdown_file.fingerprint}
            save_state(state)
            continue

        embeddings = model.encode(docs, normalize_embeddings=True).tolist()
        if collection is not None:
            collection.upsert(ids=ids, documents=docs, embeddings=embeddings, metadatas=metas)

        records = [
            {"id": id_, "document": doc, "embedding": embedding, "metadata": meta}
            for id_, doc, embedding, meta in zip(ids, docs, embeddings, metas)
        ]
        write_embeddings_to_s3(records, fernet)
        write_embeddings_to_local(records, fernet)
        state[markdown_file.rel] = {"fingerprint": markdown_file.fingerprint}
        save_state(state)
        print(f"Indexed {len(docs)} chunks from {markdown_file.rel}")


if __name__ == "__main__":
    main()
