import hashlib
import os
import re
from dataclasses import dataclass
from datetime import date
from itertools import chain
from pathlib import Path
from typing import Iterable

from cryptography.fernet import Fernet
from dotenv import load_dotenv

load_dotenv()

DATE_STEM_RE = re.compile(r"^(\d{4})_(\d{2})_(\d{2})$")


@dataclass(frozen=True)
class MarkdownFile:
    rel: str  # relative path
    fingerprint: str
    text: str


def getenv_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


def required_env(name: str) -> str:
    value = os.getenv(name)
    if not value:
        raise ValueError(f"{name} must be set")
    return value


def build_fernet_from_env() -> Fernet | None:
    key_value = os.getenv("S3_ENCRYPTION_KEY")
    if not key_value:
        raise ValueError("S3_ENCRYPTION_KEY env var is missing")

    try:
        return Fernet(key_value.encode("utf-8"))
    except Exception as exc:
        raise ValueError("S3_ENCRYPTION_KEY must be a Fernet key generated by Fernet.generate_key()") from exc


def _bytes(data: bytes | str) -> bytes:
    if isinstance(data, bytes):
        return data
    return data.encode("utf-8")


def decrypt_if_needed(data: bytes | str, fernet: Fernet | None) -> bytes:
    if fernet is None:
        return _bytes(data)
    return fernet.decrypt(_bytes(data))


def encrypt_if_needed(data: bytes | str, fernet: Fernet | None) -> bytes:
    if fernet is None:
        return _bytes(data)
    return fernet.encrypt(_bytes(data))


def date_from_rel(rel: str) -> date | None:
    match = DATE_STEM_RE.match(Path(rel).stem)
    if not match:
        return None
    year, month, day = [int(part) for part in match.groups()]
    return date(year, month, day)


def in_date_window(rel: str) -> bool:
    file_date = date_from_rel(rel)
    if file_date is None:
        return True

    start = os.getenv("SHARD_DATE_START")
    end = os.getenv("SHARD_DATE_END")
    if start and file_date < date.fromisoformat(start):
        return False
    if end and file_date > date.fromisoformat(end):
        return False
    return True


def in_hash_shard(rel: str) -> bool:
    count = int(os.getenv("SHARD_COUNT", "1"))
    index = int(os.getenv("SHARD_INDEX", "0"))
    if count < 1:
        raise ValueError("SHARD_COUNT must be at least 1")
    if index < 0 or index >= count:
        raise ValueError("SHARD_INDEX must be between 0 and SHARD_COUNT - 1")
    digest = hashlib.sha256(rel.encode("utf-8")).digest()
    return int.from_bytes(digest[:8], "big") % count == index


def should_index_rel(rel: str) -> bool:
    return in_date_window(rel) and in_hash_shard(rel)


def iter_local_markdown(fernet: Fernet | None = None) -> Iterable[MarkdownFile]:
    logseq_dir = Path(required_env("LOGSEQ_DIR"))
    patterns = [pattern.strip() for pattern in os.getenv("LOCAL_MARKDOWN_GLOBS", "journals/*.md").split(",")]
    paths = chain.from_iterable(logseq_dir.rglob(pattern) for pattern in patterns if pattern)

    for path in paths:
        rel = str(path.relative_to(logseq_dir))
        if not should_index_rel(rel):
            continue

        body = path.read_bytes()
        plaintext = decrypt_if_needed(body, fernet)

        yield MarkdownFile(
            rel=rel,
            fingerprint=str(path.stat().st_mtime),
            text=plaintext.decode("utf-8", errors="ignore"),
        )
